# Generated by Django 5.0.6 on 2024-08-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('reader', 'Reader'), ('admin', 'Admin')], default='reader', max_length=10),
        ),
    ]
