# Generated by Django 5.0.6 on 2024-08-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
